instance:
  url: "https://issues.redhat.com"
  browse_pattern: "https://issues.redhat.com/browse/{key}"

prefixes:
  - "CNV"
  - "VIRTSTRAT"
  - "OCPBUGS"

custom_fields:
  feature_link: "Feature Link"
  git_pull_request: "Git Pull Request"

pr_url_scan_pattern: "https://github.com/.*/pull/\\d+"
